tcp.timeout=120000
tcp.port=50123

udp.port=51235

persistence.user_file=src/main/resources/storedUsers.json
persistence.order_file=src/main/resources/storedOrders.json
persistence.trade_file=src/main/resources/storedTrades.json
persistence.secs=60

history.file=src/main/resources/storicoOrdini.json